#ifndef MessageTypeDef_h
#define MessageTypeDef_h


/**消息类型表
USERMESSAGE_BEGIN为最后一个系统消息,用户消息的编号由它开始
*/

//tolua_begin
enum MessageType 
{
	APPLICATION_NULL,
	APPLICATION_INIT,
	APPLICATION_END,
	GUIMANAGER_REGISTER_UI,
	GUIMANAGER_UNREGISTER_UI,
	GUIMANAGER_Show_UI,
	GUIMANAGER_Hide_UI,
	INPUTSYSTEM_KEY_PRESS,
	INPUTSYSTEM_KEY_RELEASE,
	INPUTSYSTEM_GESTURE_BEGIN,
	INPUTSYSTEM_GESTURE_END,
	INPUTSYSTEM_GESTURE_STARTDETECTION,
	INPUTSYSTEM_GESTURE_BREAKDETECTION,
	INPUTSYSTEM_GESTURE_DETECTING,
	INPUTSYSTEM_USER_ENTER,
	INPUTSYSTEM_USER_LEAVE,
	INPUTSYSTEM_CALIBRATION_START,
	INPUTSYSTEM_CALIBRATION_SUCCEED,
	BODYSENSERWIDGET_SUCCEED,

	IMAGENUMBER_SCROLLEND,
	ScrollGallery_Message,
	AudioManager_MusicEnd,
	ACTION_BEGIN, //动作开始
	ACTION_END  ,  //动作结束
	MIX_ACTION_BEGIN,//混合动作开始
	MIX_ACTION_END,//混合动作结束
	ACTION_KEY_EVENT, //注册的关键帧事件

	GESTURE_WASH,
	GESTURE_HANDUP,
	GESTURE_MOVELEFT,
	GESTURE_MOVERIGHT,
	GESTURE_CANCEL,
	GESTURE_OK,
	GESTURE_ITEM,

	USERMESSAGE_BEGIN
};
//tolua_end

#endif //MessageTypeDef_h